window:
  dynamic_padding: true
  decorations: none
  startup_mode: Fullscreen
font:
  normal:
    family: Source Code Pro
    style: SemiBold
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic
  bold_italic:
    family: Source Code Pro
    style: Bold Italic
  size: 9.0
draw_bold_text_with_bright_colors: true

# Colors (Monokai Dark)
colors:
  # Default colors
  primary:
    background: '#272822'
    foreground: '#F8F8F2'

  # Normal colors
  normal:
   black:   '#272822'
   red:     '#F92672'
   green:   '#A6E22E'
   yellow:  '#F4BF75'
   blue:    '#66D9EF'
   magenta: '#AE81FF'
   cyan:    '#A1EFE4'
   white:   '#F8F8F2'

  # Bright colors
  bright:
   black:   '#75715E'
   red:     '#F92672'
   green:   '#A6E22E'
   yellow:  '#F4BF75'
   blue:    '#66D9EF'
   magenta: '#AE81FF'
   cyan:    '#A1EFE4'
   white:   '#F9F8F5'
background_opacity: 0.95
live_config_reload: true
hide_when_typing: true

# shell:
#   program: zsh
#   args:
#     - -l
#     - -c
#     - "tmux new-session -A -s audacioustux"
