# Don't print a new line at the start of the prompt
add_newline = false

[username]
show_always = true

[character]
symbol = "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ ❯"
error_symbol = "(ง •̀_•́)ง ❯"
style_success = "bold blue"
use_symbol_for_status = true

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

